package es.udc.fic.csi2122.baserest.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;


/**
 * The Client entity
 *
 * @author jorge.arias@udc.es
 */

@Entity
public class Client {

    /** Entity id, autogenerated */
    @Id
    @GeneratedValue
    private Long id;

    /** The client name.*/
    @Column
    private String name;

    /** The client surname or surnames */
    @Column
    private String surname;

    /** The client email
     * In this application, email is unique
     * */
    @Column(unique = true)
    private String email;

    /** The client paying methods */
    @Column
    private String payMethods;



    /** Empty constructor as required by JPA */
    public Client() {
    }

    /**
     * Convenience constructor for new clients. Id is not set
     *
     * @param name the user name
     * @param surname  the user age
     * @param email
     * @param payMethods
     */
    public Client(String name, String surname,String email, String payMethods) {
        this.name = name;
        this.surname = surname;
        this.email=email;
        this.payMethods=payMethods;
    }

    /**
     * Get the client id
     *
     * @return the client id
     */

    public Long getId() {
        return id;
    }

    /**
     * Set the client id
     *
     * @param id the new client id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Get the client name
     *
     * @return the client name
     */
    public String getName() {
        return name;
    }

    /**
     * Set the client name
     *
     * @param name the new client name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Get the client surname or surnames
     *
     * @return the client surname or surnames
     */
    public String getSurname() {
        return surname;
    }

    /**
     * Set the user surnames
     *
     * @param surname the new client surnames
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * Get the client email
     *
     * @return the client email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Set the client email
     *
     * @param email the new client email
     */
    public void setEmail(String email) {
        this.email = email;
    }


    /**
     * Get the client pay methods
     *
     * @return the client pay methods
     */
    public String getPayMethods() {
        return payMethods;
    }

    /**
     * Set the client pay methods
     *
     * @param payMethods the new client pay methods
     */
    public void setPayMethods(String payMethods) {
        this.payMethods = payMethods;
    }

    /**
     * Overridden toString for debugging
     */
    @Override
    public String toString() {
        return "User[id=" + id + ", name=" + name + ", surname/s=" + surname +
                ", email=" + email + ", pay method/s="+payMethods +"]"
                ;}
}
